# /// script
# requires-python = ">=3.11"
# dependencies = ["pyyaml>=6"]
# ///
"""Generates the Kubernetes manifests under deploy/k8s from one service table.

    uv run deploy/k8s/generate.py

Output (committed): base/ (services), components/monitoring (ServiceMonitor, PrometheusRule from
config/prometheus/alerts.yml, Grafana dashboard ConfigMaps from config/grafana/dashboards),
components/keda (lag-based autoscaling), overlays/local (kind: + infra), overlays/prod-aws.
"""

import math
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent
REPO = ROOT.parents[1]
NS = "recsys"


class Literal(str):
    pass


yaml.add_representer(Literal, lambda d, v: d.represent_scalar("tag:yaml.org,2002:str", v, style="|"))
yaml.add_representer(str, lambda d, v: d.represent_scalar("tag:yaml.org,2002:str", v, style='"' if v in ("true", "false", "on", "off", "yes", "no") or v.isdigit() else None))


def dump(path: Path, docs):
    path.parent.mkdir(parents=True, exist_ok=True)
    docs = docs if isinstance(docs, list) else [docs]
    path.write_text(
        "# Generated by deploy/k8s/generate.py — edit the generator, not this file.\n"
        + "---\n".join(yaml.dump(d, sort_keys=False, width=120) for d in docs)
    )


# ------------------------------------------------------------------ service table (production base)
SERVICES = {
    "recommendation-api": dict(port=8080, replicas=6, cpu="1", memory="1536Mi", hpa=(6, 60, 60), public=True, models=True, pdb=4, public_latency_critical=True),
    "ingestion-api": dict(port=8081, replicas=3, cpu="500m", memory="768Mi", hpa=(3, 30, 60), public=True, pdb=2),
    "catalog-service": dict(port=8082, replicas=2, cpu="500m", memory="768Mi", pdb=1, env={"POSTGRES_URL": "$(POSTGRES_URL)"}),
    "stream-processor": dict(
        port=8083, replicas=6, cpu="2", memory="4Gi", stateful=True, state_volume="50Gi", pdb=5,
        java_opts="-XX:MaxRAMPercentage=40 -XX:MaxDirectMemorySize=96m -XX:+UseG1GC -XX:+ExitOnOutOfMemoryError",
        env={"STREAMS_STATE_DIR": "/var/lib/recs-streams", "STREAMS_NUM_THREADS": "4", "STREAMS_STANDBY_REPLICAS": "1",
             "RECS_ROCKSDB_CACHE_MB": "512", "RECS_ROCKSDB_MEMTABLE_MB": "128"},
    ),
    "embedding-worker": dict(port=8084, replicas=2, cpu="500m", memory="1Gi", pdb=1, keda=("catalog-embedder", "catalog.items.v1", 1, 12)),
    "enrichment-worker": dict(port=8086, replicas=1, cpu="500m", memory="768Mi", pdb=0, keda=("item-enricher", "catalog.items.v1", 1, 6)),
}

COMMON_ENV_FROM = [{"configMapRef": {"name": "recsys-config"}}, {"secretRef": {"name": "recsys-secrets"}}]


def labels(name):
    return {"app.kubernetes.io/name": name, "app.kubernetes.io/part-of": "recsys"}


def container(name, s):
    cpus = max(2, math.ceil(float(s["cpu"].rstrip("m")) / (1000 if s["cpu"].endswith("m") else 1)) * 2)
    opts = s.get("java_opts", "-XX:MaxRAMPercentage=60 -XX:MaxDirectMemorySize=96m -XX:+UseG1GC -XX:MaxGCPauseMillis=20 -XX:+ExitOnOutOfMemoryError")
    # Size JVM ergonomics (GC/JIT threads, netty loops, virtual-thread carriers) to ~2x the CPU
    # request: with no CPU limit the JVM would otherwise size everything for the whole node.
    # The serving API is exempt: capping it also cut G1's parallel GC threads and lengthened young
    # pauses past the latency budget under load (docs/load-test-results.md).
    if not s.get("public_latency_critical"):
        opts += f" -XX:ActiveProcessorCount={cpus}"
    env = [{"name": "JAVA_OPTS", "value": opts}]
    # glibc keeps up to 8 x CPUs malloc arenas; with many native-allocating threads (netty, gRPC,
    # RocksDB) that was ~250 MB of untracked RSS per pod and OOM kills under load. Two is plenty.
    env.append({"name": "MALLOC_ARENA_MAX", "value": "2"})
    env += [{"name": k, "value": v} for k, v in s.get("env", {}).items()]
    if s.get("stateful"):
        env.append({"name": "HOSTNAME", "valueFrom": {"fieldRef": {"fieldPath": "metadata.name"}}})  # static membership
    mounts = [{"name": "tmp", "mountPath": "/tmp"}]
    if s.get("stateful"):
        mounts.append({"name": "state", "mountPath": "/var/lib/recs-streams"})
    if s.get("models"):
        mounts.append({"name": "models", "mountPath": "/models", "readOnly": True})
    probe = lambda path: {"httpGet": {"path": path, "port": "http"}, "periodSeconds": 10, "timeoutSeconds": 3}
    return {
        "name": name,
        "image": f"recsys/{name}:latest",
        "imagePullPolicy": "IfNotPresent",
        "ports": [{"name": "http", "containerPort": s["port"]}],
        "envFrom": COMMON_ENV_FROM,
        "env": env,
        "resources": {
            # No CPU limit: throttling hurts tail latency; memory limit = request (Guaranteed memory).
            "requests": {"cpu": s["cpu"], "memory": s["memory"]},
            "limits": {"memory": s["memory"]},
        },
        "startupProbe": {**probe("/actuator/health/liveness"), "failureThreshold": 30, "periodSeconds": 5},
        "livenessProbe": {**probe("/actuator/health/liveness"), "failureThreshold": 3},
        "readinessProbe": {**probe("/actuator/health/readiness"), "failureThreshold": 3},
        # Let endpoints/load balancers drop the pod before graceful shutdown starts.
        "lifecycle": {"preStop": {"exec": {"command": ["sleep", "10"]}}},
        "securityContext": {
            "runAsNonRoot": True,
            "runAsUser": 10001,
            "allowPrivilegeEscalation": False,
            "readOnlyRootFilesystem": True,
            "capabilities": {"drop": ["ALL"]},
            "seccompProfile": {"type": "RuntimeDefault"},
        },
        "volumeMounts": mounts,
    }


def workload(name, s):
    volumes = [{"name": "tmp", "emptyDir": {}}]
    if s.get("models"):
        volumes.append({"name": "models", "emptyDir": {}})  # filled by the model-sync sidecar (prod) / hostPath (local)
    pod = {
        "metadata": {"labels": labels(name), "annotations": {"prometheus.io/scrape": "true", "prometheus.io/port": str(s["port"]), "prometheus.io/path": "/actuator/prometheus"}},
        "spec": {
            "serviceAccountName": "recsys",
            # No docker-link env vars (KAFKA_PORT=tcp://… breaks the Kafka image; REDIS_PORT etc. could
            # collide with app config).
            "enableServiceLinks": False,
            "terminationGracePeriodSeconds": 45,
            "securityContext": {"fsGroup": 10001, "runAsNonRoot": True, "seccompProfile": {"type": "RuntimeDefault"}},
            "topologySpreadConstraints": [
                {"maxSkew": 1, "topologyKey": "topology.kubernetes.io/zone", "whenUnsatisfiable": "ScheduleAnyway", "labelSelector": {"matchLabels": labels(name)}},
                {"maxSkew": 1, "topologyKey": "kubernetes.io/hostname", "whenUnsatisfiable": "ScheduleAnyway", "labelSelector": {"matchLabels": labels(name)}},
            ],
            "containers": [container(name, s)],
            "volumes": volumes,
        },
    }
    spec = {"replicas": s["replicas"], "selector": {"matchLabels": labels(name)}, "template": pod}
    if s.get("stateful"):
        spec.update(
            serviceName=f"{name}-headless",
            podManagementPolicy="Parallel",
            updateStrategy={"type": "RollingUpdate"},
            volumeClaimTemplates=[{
                "metadata": {"name": "state"},
                "spec": {"accessModes": ["ReadWriteOnce"], "resources": {"requests": {"storage": s["state_volume"]}}},
            }],
        )
        kind = "StatefulSet"
    else:
        spec["strategy"] = {"type": "RollingUpdate", "rollingUpdate": {"maxUnavailable": 0, "maxSurge": "25%"}}
        kind = "Deployment"
    return {"apiVersion": "apps/v1", "kind": kind, "metadata": {"name": name, "labels": labels(name)}, "spec": spec}


def service(name, s, headless=False):
    spec = {"selector": labels(name), "ports": [{"name": "http", "port": s["port"], "targetPort": "http"}]}
    if headless:
        spec["clusterIP"] = "None"
    return {"apiVersion": "v1", "kind": "Service", "metadata": {"name": f"{name}-headless" if headless else name, "labels": labels(name)}, "spec": spec}


def hpa(name, s):
    lo, hi, cpu = s["hpa"]
    return {
        "apiVersion": "autoscaling/v2",
        "kind": "HorizontalPodAutoscaler",
        "metadata": {"name": name},
        "spec": {
            "scaleTargetRef": {"apiVersion": "apps/v1", "kind": "Deployment", "name": name},
            "minReplicas": lo,
            "maxReplicas": hi,
            "metrics": [{"type": "Resource", "resource": {"name": "cpu", "target": {"type": "Utilization", "averageUtilization": cpu}}}],
            "behavior": {
                "scaleUp": {"stabilizationWindowSeconds": 0, "policies": [{"type": "Percent", "value": 100, "periodSeconds": 30}]},
                "scaleDown": {"stabilizationWindowSeconds": 300, "policies": [{"type": "Percent", "value": 20, "periodSeconds": 60}]},
            },
        },
    }


def pdb(name, s):
    return {"apiVersion": "policy/v1", "kind": "PodDisruptionBudget", "metadata": {"name": name},
            "spec": {"minAvailable": s["pdb"], "selector": {"matchLabels": labels(name)}}}


def base():
    out = ROOT / "base"
    resources = ["namespace.yaml", "rbac.yaml", "network-policy.yaml", "topics-job.yaml"]
    dump(out / "namespace.yaml", {"apiVersion": "v1", "kind": "Namespace", "metadata": {"name": NS, "labels": {"pod-security.kubernetes.io/enforce": "restricted"}}})
    dump(out / "rbac.yaml", {"apiVersion": "v1", "kind": "ServiceAccount", "metadata": {"name": "recsys"}, "automountServiceAccountToken": False})
    # Generated with a content hash in its name, so a config change rolls every pod that uses it.
    config = {
        "data": {
            # Overlays patch these to real endpoints (MSK, ElastiCache, RDS, Qdrant).
            "KAFKA_BOOTSTRAP": "kafka:29092",
            "SCHEMA_REGISTRY_URL": "http://schema-registry:8081",
            "SCHEMA_AUTO_REGISTER": "false",
            "REDIS_URI": "redis://redis:6379",
            "QDRANT_HOST": "qdrant",
            "QDRANT_GRPC_PORT": "6334",
            "POSTGRES_URL": "jdbc:postgresql://postgres:5432/recsys",
            "CATALOG_URL": "http://catalog-service:8082",
            "RECS_INDEX_VERSION": "items_te3s_512_v1",
            "RECS_EMBEDDINGS_TOPIC": "catalog.embeddings.v1",
            "RECS_OPENAI_MODE": "openai",
            "RECS_MODEL_DIR": "/models",
            "RECS_SECURITY_MODE": "jwt-or-api-key",
            "KAFKA_REPLICATION_FACTOR": "3",
            "LOG_FORMAT": "ecs",
            "TRACING_SAMPLING": "0.05",
            "MANAGEMENT_OTLP_TRACING_ENDPOINT": "http://otel-collector.observability:4318/v1/traces",
        },
    }
    dump(out / "network-policy.yaml", [
        {"apiVersion": "networking.k8s.io/v1", "kind": "NetworkPolicy", "metadata": {"name": "default-deny-ingress"},
         "spec": {"podSelector": {}, "policyTypes": ["Ingress"]}},
        {"apiVersion": "networking.k8s.io/v1", "kind": "NetworkPolicy", "metadata": {"name": "allow-intra-namespace"},
         "spec": {"podSelector": {}, "ingress": [{"from": [{"podSelector": {}}]}]}},
        {"apiVersion": "networking.k8s.io/v1", "kind": "NetworkPolicy", "metadata": {"name": "allow-public-apis-from-ingress"},
         "spec": {"podSelector": {"matchExpressions": [{"key": "app.kubernetes.io/name", "operator": "In", "values": ["recommendation-api", "ingestion-api"]}]},
                  "ingress": [{"from": [{"namespaceSelector": {"matchLabels": {"kubernetes.io/metadata.name": "ingress"}}}]}]}},
        {"apiVersion": "networking.k8s.io/v1", "kind": "NetworkPolicy", "metadata": {"name": "allow-prometheus-scrape"},
         "spec": {"podSelector": {"matchLabels": {"app.kubernetes.io/part-of": "recsys"}},
                  "ingress": [{"from": [{"namespaceSelector": {"matchLabels": {"kubernetes.io/metadata.name": "monitoring"}}}]}]}},
    ])
    topics_conf = (REPO / "config/kafka/topics.prod.conf").read_text()
    script = (REPO / "config/kafka/create-topics.sh").read_text()
    dump(out / "topics-job.yaml", [
        {"apiVersion": "v1", "kind": "ConfigMap", "metadata": {"name": "kafka-topics"}, "data": {"topics.conf": Literal(topics_conf), "create-topics.sh": Literal(script)}},
        {"apiVersion": "batch/v1", "kind": "Job", "metadata": {"name": "kafka-topics"},
         "spec": {"backoffLimit": 20, "ttlSecondsAfterFinished": 3600, "template": {"metadata": {"labels": {"app.kubernetes.io/name": "kafka-topics"}}, "spec": {
             "restartPolicy": "OnFailure", "enableServiceLinks": False,
             "securityContext": {"runAsNonRoot": True, "runAsUser": 1000, "seccompProfile": {"type": "RuntimeDefault"}},
             "containers": [{"name": "create-topics", "image": "confluentinc/cp-kafka:7.9.10",
                             "command": ["bash", "/config/create-topics.sh", "$(KAFKA_BOOTSTRAP)", "/config/topics.conf"],
                             "env": [{"name": "REPLICATION_FACTOR", "valueFrom": {"configMapKeyRef": {"name": "recsys-config", "key": "KAFKA_REPLICATION_FACTOR"}}},
                                     {"name": "KAFKA_BOOTSTRAP", "valueFrom": {"configMapKeyRef": {"name": "recsys-config", "key": "KAFKA_BOOTSTRAP"}}}],
                             "securityContext": {"allowPrivilegeEscalation": False, "capabilities": {"drop": ["ALL"]}},
                             "volumeMounts": [{"name": "config", "mountPath": "/config"}]}],
             "volumes": [{"name": "config", "configMap": {"name": "kafka-topics"}}]}}}},
    ])
    for name, s in SERVICES.items():
        docs = [workload(name, s), service(name, s)]
        if s.get("stateful"):
            docs.append(service(name, s, headless=True))
        if s.get("hpa"):
            docs.append(hpa(name, s))
        if s.get("pdb"):
            docs.append(pdb(name, s))
        dump(out / f"{name}.yaml", docs)
        resources.append(f"{name}.yaml")
    dump(out / "kustomization.yaml", {"apiVersion": "kustomize.config.k8s.io/v1beta1", "kind": "Kustomization", "namespace": NS, "resources": resources,
                                         "configMapGenerator": [{"name": "recsys-config", "literals": [f"{k}={v}" for k, v in config["data"].items()]}]})


def monitoring():
    out = ROOT / "components/monitoring"
    alerts = yaml.safe_load((REPO / "config/prometheus/alerts.yml").read_text())
    dump(out / "prometheusrule.yaml", {"apiVersion": "monitoring.coreos.com/v1", "kind": "PrometheusRule",
        "metadata": {"name": "recsys-alerts", "labels": {"release": "kube-prometheus-stack"}}, "spec": alerts})
    dump(out / "servicemonitor.yaml", {"apiVersion": "monitoring.coreos.com/v1", "kind": "ServiceMonitor",
        "metadata": {"name": "recsys", "labels": {"release": "kube-prometheus-stack"}},
        "spec": {"selector": {"matchLabels": {"app.kubernetes.io/part-of": "recsys"}},
                 "endpoints": [{"port": "http", "path": "/actuator/prometheus", "interval": "15s",
                                "relabelings": [{"targetLabel": "job", "replacement": "recsys"}]}]}})
    dashboards = []
    for f in sorted((REPO / "config/grafana/dashboards").glob("*.json")):
        dashboards.append({"apiVersion": "v1", "kind": "ConfigMap",
                           "metadata": {"name": f"grafana-dashboard-{f.stem}", "labels": {"grafana_dashboard": "1"}, "annotations": {"grafana_folder": "Recsys"}},
                           "data": {f.name: Literal(f.read_text())}})
    dump(out / "dashboards.yaml", dashboards)
    dump(out / "kustomization.yaml", {"apiVersion": "kustomize.config.k8s.io/v1alpha1", "kind": "Component",
                                      "resources": ["prometheusrule.yaml", "servicemonitor.yaml", "dashboards.yaml"]})


def keda():
    out = ROOT / "components/keda"
    docs = []
    for name, s in SERVICES.items():
        if not s.get("keda"):
            continue
        group, topic, lo, hi = s["keda"]
        docs.append({"apiVersion": "keda.sh/v1alpha1", "kind": "ScaledObject", "metadata": {"name": name},
                     "spec": {"scaleTargetRef": {"name": name}, "minReplicaCount": lo, "maxReplicaCount": hi,
                              "cooldownPeriod": 300,
                              "triggers": [{"type": "kafka", "metadata": {
                                  "bootstrapServers": "kafka:29092", "consumerGroup": group, "topic": topic,
                                  # Scale out when lag per replica exceeds this; never beyond the partition count.
                                  "lagThreshold": "500", "allowIdleConsumers": "false"}}]}})
    # Stream processor: scale on lag of the raw event topic, bounded by partitions (48), slowly —
    # every scale event is a rebalance + state restore (standby replicas make it cheap).
    docs.append({"apiVersion": "keda.sh/v1alpha1", "kind": "ScaledObject", "metadata": {"name": "stream-processor"},
                 "spec": {"scaleTargetRef": {"kind": "StatefulSet", "name": "stream-processor"}, "minReplicaCount": 6, "maxReplicaCount": 12,
                          "cooldownPeriod": 900, "pollingInterval": 60,
                          "advanced": {"horizontalPodAutoscalerConfig": {"behavior": {
                              "scaleUp": {"stabilizationWindowSeconds": 300, "policies": [{"type": "Pods", "value": 2, "periodSeconds": 300}]},
                              "scaleDown": {"stabilizationWindowSeconds": 1800, "policies": [{"type": "Pods", "value": 1, "periodSeconds": 900}]}}}},
                          "triggers": [{"type": "kafka", "metadata": {"bootstrapServers": "kafka:29092", "consumerGroup": "recs-stream-processor",
                                                                       "topic": "events.raw.v1", "lagThreshold": "20000"}}]}})
    dump(out / "scaledobjects.yaml", docs)
    dump(out / "kustomization.yaml", {"apiVersion": "kustomize.config.k8s.io/v1alpha1", "kind": "Component", "resources": ["scaledobjects.yaml"]})


INFRA_ENV_KAFKA = {
    "KAFKA_NODE_ID": "1", "KAFKA_PROCESS_ROLES": "broker,controller",
    "KAFKA_LISTENERS": "PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093",
    "KAFKA_ADVERTISED_LISTENERS": "PLAINTEXT://kafka:29092",
    "KAFKA_LISTENER_SECURITY_PROTOCOL_MAP": "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT",
    "KAFKA_CONTROLLER_QUORUM_VOTERS": "1@localhost:29093", "KAFKA_CONTROLLER_LISTENER_NAMES": "CONTROLLER",
    "KAFKA_INTER_BROKER_LISTENER_NAME": "PLAINTEXT", "KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR": "1",
    "KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR": "1", "KAFKA_TRANSACTION_STATE_LOG_MIN_ISR": "1",
    "KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS": "0", "KAFKA_AUTO_CREATE_TOPICS_ENABLE": "false",
    "CLUSTER_ID": "MkU3OEVBNTcwNTJENDM2Qk", "KAFKA_HEAP_OPTS": "-Xms256m -Xmx640m",
}


def infra(name, image, port, env=None, extra_ports=(), memory="512Mi", args=None, probe=None, volume=None):
    c = {"name": name, "image": image, "ports": [{"name": "main", "containerPort": port}] + [{"name": f"p{p}", "containerPort": p} for p in extra_ports],
         "env": [{"name": k, "value": v} for k, v in (env or {}).items()],
         "resources": {"requests": {"cpu": "50m", "memory": "128Mi"}, "limits": {"memory": memory}}}
    if args:
        c["args"] = args
    if probe:
        c["readinessProbe"] = probe
    pod = {"metadata": {"labels": {"app.kubernetes.io/name": name}}, "spec": {"enableServiceLinks": False, "containers": [c]}}
    pvc = None
    if volume:
        # PVC (kind: local-path), not emptyDir: a config change recreates the pod and must not wipe
        # the vector index or the catalog.
        c["volumeMounts"] = [{"name": "data", "mountPath": volume, **({"subPath": "data"} if name == "postgres" else {})}]
        pod["spec"]["volumes"] = [{"name": "data", "persistentVolumeClaim": {"claimName": f"{name}-data"}}]
        pvc = {"apiVersion": "v1", "kind": "PersistentVolumeClaim", "metadata": {"name": f"{name}-data"},
               "spec": {"accessModes": ["ReadWriteOnce"], "resources": {"requests": {"storage": "5Gi"}}}}
    dep = {"apiVersion": "apps/v1", "kind": "Deployment", "metadata": {"name": name},
           "spec": {"replicas": 1, "selector": {"matchLabels": {"app.kubernetes.io/name": name}}, "strategy": {"type": "Recreate"}, "template": pod}}
    svc = {"apiVersion": "v1", "kind": "Service", "metadata": {"name": name},
           "spec": {"selector": {"app.kubernetes.io/name": name}, "ports": [{"name": "main", "port": port, "targetPort": port}] + [{"name": f"p{p}", "port": p, "targetPort": p} for p in extra_ports]}}
    return [dep, svc] + ([pvc] if pvc else [])


def local():
    out = ROOT / "overlays/local"
    tcp = lambda p: {"tcpSocket": {"port": p}, "periodSeconds": 5}
    docs = []
    docs += infra("kafka", "confluentinc/cp-kafka:7.9.10", 29092, INFRA_ENV_KAFKA, memory="1Gi", probe=tcp(29092))
    docs += infra("schema-registry", "confluentinc/cp-schema-registry:7.9.10", 8081, {
        "SCHEMA_REGISTRY_HOST_NAME": "schema-registry", "SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS": "kafka:29092",
        "SCHEMA_REGISTRY_LISTENERS": "http://0.0.0.0:8081", "SCHEMA_REGISTRY_SCHEMA_COMPATIBILITY_LEVEL": "backward",
        "SCHEMA_REGISTRY_HEAP_OPTS": "-Xms128m -Xmx256m"}, probe={"httpGet": {"path": "/subjects", "port": 8081}, "periodSeconds": 5})
    docs += infra("redis", "redis:7.4-alpine", 6379, args=["--save", "", "--appendonly", "no", "--maxmemory", "256mb", "--maxmemory-policy", "volatile-lru"], memory="320Mi", probe=tcp(6379))
    docs += infra("qdrant", "qdrant/qdrant:v1.19.1", 6333, extra_ports=(6334,), memory="1Gi", probe=tcp(6334), volume="/qdrant/storage")
    docs += infra("postgres", "postgres:16-alpine", 5432, {"POSTGRES_DB": "recsys", "POSTGRES_USER": "recsys", "POSTGRES_PASSWORD": "recsys"}, memory="256Mi", probe=tcp(5432), volume="/var/lib/postgresql/data")
    docs += infra("jaeger", "jaegertracing/jaeger:2.21.0", 16686, extra_ports=(4318,), memory="512Mi", probe=tcp(4318))
    # Schema auto-registration is on locally (prod registers contracts from CI).
    dump(out / "infra.yaml", docs)
    small = lambda name, mem: {"target": {"kind": "StatefulSet" if name == "stream-processor" else "Deployment", "name": name},
                               "patch": yaml.dump([
                                   {"op": "replace", "path": "/spec/replicas", "value": 1},
                                   {"op": "replace", "path": "/spec/template/spec/containers/0/resources", "value": {"requests": {"cpu": "100m", "memory": "256Mi"}, "limits": {"memory": mem}}},  # kind on a laptop: burstable
                                   {"op": "replace", "path": "/spec/template/spec/containers/0/image", "value": f"recsys/{name}:local"},
                               ])}
    patches = [small(n, m) for n, m in [("recommendation-api", "1Gi"), ("ingestion-api", "512Mi"), ("catalog-service", "512Mi"),
                                         ("stream-processor", "1280Mi"), ("embedding-worker", "640Mi"), ("enrichment-worker", "512Mi")]]
    patches += [
        {"target": {"kind": "StatefulSet", "name": "stream-processor"}, "patch": yaml.dump([
            {"op": "replace", "path": "/spec/volumeClaimTemplates/0/spec/resources/requests/storage", "value": "1Gi"},
            {"op": "replace", "path": "/spec/template/spec/containers/0/env", "value": [
                {"name": "JAVA_OPTS", "value": "-XX:MaxRAMPercentage=40 -XX:MaxDirectMemorySize=96m -XX:+UseG1GC -XX:+ExitOnOutOfMemoryError -XX:ActiveProcessorCount=2"},
                {"name": "MALLOC_ARENA_MAX", "value": "2"},
                {"name": "STREAMS_STATE_DIR", "value": "/var/lib/recs-streams"}, {"name": "RECS_ROCKSDB_CACHE_MB", "value": "64"},
                {"name": "RECS_ROCKSDB_MEMTABLE_MB", "value": "32"},
                {"name": "HOSTNAME", "valueFrom": {"fieldRef": {"fieldPath": "metadata.name"}}}]},
        ])},
        # Models from the host checkout (kind extraMounts ml/models → /models on the node).
        {"target": {"kind": "Deployment", "name": "recommendation-api"}, "patch": yaml.dump([
            {"op": "replace", "path": "/spec/template/spec/volumes/1", "value": {"name": "models", "hostPath": {"path": "/models", "type": "DirectoryOrCreate"}}}])},
        {"target": {"kind": "HorizontalPodAutoscaler"}, "patch": yaml.dump([{"op": "replace", "path": "/spec/minReplicas", "value": 1}, {"op": "replace", "path": "/spec/maxReplicas", "value": 2}])},
        {"target": {"kind": "Namespace", "name": NS}, "patch": yaml.dump([
            {"op": "replace", "path": "/metadata/labels", "value": {"pod-security.kubernetes.io/enforce": "privileged", "pod-security.kubernetes.io/warn": "restricted"}}])},
        # Local partition counts (3) instead of prod's (48): one broker, one stream-processor pod.
        {"target": {"kind": "ConfigMap", "name": "kafka-topics"}, "patch": yaml.dump([
            {"op": "replace", "path": "/data/topics.conf", "value": (REPO / "config/kafka/topics.conf").read_text()}])},
        {"target": {"kind": "PodDisruptionBudget"}, "patch": yaml.dump([{"op": "replace", "path": "/spec/minAvailable", "value": 0}])},
        {"target": {"kind": "NetworkPolicy", "name": "allow-public-apis-from-ingress"}, "patch": yaml.dump([
            {"op": "replace", "path": "/spec/ingress/0/from", "value": [{"namespaceSelector": {}}]}])},
    ]
    dump(out / "kustomization.yaml", {
        "apiVersion": "kustomize.config.k8s.io/v1beta1", "kind": "Kustomization", "namespace": NS,
        "resources": ["../../base", "infra.yaml"],
        "configMapGenerator": [{"name": "recsys-config", "behavior": "merge", "literals": [
            "RECS_INDEX_VERSION=items_mock_512_v2", "RECS_OPENAI_MODE=mock", "RECS_SECURITY_MODE=api-key",
            "KAFKA_REPLICATION_FACTOR=1", "SCHEMA_AUTO_REGISTER=true", "MANAGEMENT_OTLP_TRACING_ENDPOINT=http://jaeger:4318/v1/traces", "TRACING_SAMPLING=0.01",
            "RECS_FEATURE_LOG_SAMPLE_RATE=0.5"]}],
        "secretGenerator": [{"name": "recsys-secrets", "literals": ["RECS_API_KEYS=dev-key", "RECS_API_KEY=dev-key", "POSTGRES_USER=recsys",
                                                                    "POSTGRES_PASSWORD=recsys", "OPENAI_API_KEY=", "EXPORT_HMAC_SECRET=local-dev-only"]}],
        "patches": patches,
    })
    (out / "kind-config.yaml").write_text(
        "# kind create cluster --name recsys --config deploy/k8s/overlays/local/kind-config.yaml\n"
        "kind: Cluster\napiVersion: kind.x-k8s.io/v1alpha4\nnodes:\n  - role: control-plane\n"
        "    extraMounts:\n      - hostPath: ./ml/models\n        containerPath: /models\n        readOnly: true\n"
    )


def prod():
    out = ROOT / "overlays/prod-aws"
    account = "123456789012.dkr.ecr.us-east-1.amazonaws.com"
    dump(out / "external-secrets.yaml", {
        "apiVersion": "external-secrets.io/v1", "kind": "ExternalSecret", "metadata": {"name": "recsys-secrets"},
        "spec": {"refreshInterval": "1h", "secretStoreRef": {"kind": "ClusterSecretStore", "name": "aws-secrets-manager"},
                 "target": {"name": "recsys-secrets"},
                 "dataFrom": [{"extract": {"key": "prod/recsys"}}]},  # keys: OPENAI_API_KEY, RECS_API_KEYS, POSTGRES_*, EXPORT_HMAC_SECRET
    })
    dump(out / "ingress.yaml", {
        "apiVersion": "networking.k8s.io/v1", "kind": "Ingress", "metadata": {"name": "recsys-public", "annotations": {
            "alb.ingress.kubernetes.io/scheme": "internal", "alb.ingress.kubernetes.io/target-type": "ip",
            "alb.ingress.kubernetes.io/healthcheck-path": "/actuator/health/readiness",
            # New pods start with a cold JIT (p99 ~180 ms for their first minute in the kind rollout
            # test); ramp their share of traffic instead of giving them a full share at once.
            "alb.ingress.kubernetes.io/target-group-attributes": "slow_start.duration_seconds=60,deregistration_delay.timeout_seconds=20"}},
        "spec": {"ingressClassName": "alb", "rules": [{"host": "recs.internal.example.com", "http": {"paths": [
            {"path": "/v1/recommendations", "pathType": "Prefix", "backend": {"service": {"name": "recommendation-api", "port": {"number": 8080}}}},
            {"path": "/v1/experiments", "pathType": "Prefix", "backend": {"service": {"name": "recommendation-api", "port": {"number": 8080}}}},
            {"path": "/v1/events", "pathType": "Prefix", "backend": {"service": {"name": "ingestion-api", "port": {"number": 8081}}}},
            {"path": "/v1/users", "pathType": "Prefix", "backend": {"service": {"name": "ingestion-api", "port": {"number": 8081}}}}]}}]},
    })
    # Model registry in S3: sidecar syncs models every 60 s into the shared volume (IRSA: read-only).
    sidecar = {"name": "model-sync", "image": "amazon/aws-cli:2.27.0",
               "command": ["sh", "-c", "while true; do aws s3 sync --delete s3://recsys-models-prod/ranker /models/ranker; sleep 60; done"],
               "resources": {"requests": {"cpu": "10m", "memory": "64Mi"}, "limits": {"memory": "128Mi"}},
               "securityContext": {"runAsNonRoot": True, "runAsUser": 10001, "allowPrivilegeEscalation": False, "readOnlyRootFilesystem": True, "capabilities": {"drop": ["ALL"]}},
               "env": [{"name": "HOME", "value": "/tmp"}],
               "volumeMounts": [{"name": "models", "mountPath": "/models"}, {"name": "tmp", "mountPath": "/tmp"}]}
    images = [{"name": f"recsys/{n}", "newName": f"{account}/recsys/{n}", "newTag": "2026.10.0"} for n in SERVICES]
    dump(out / "kustomization.yaml", {
        "apiVersion": "kustomize.config.k8s.io/v1beta1", "kind": "Kustomization", "namespace": NS,
        "resources": ["../../base", "external-secrets.yaml", "ingress.yaml"],
        "components": ["../../components/monitoring", "../../components/keda"],
        "images": images,
        "configMapGenerator": [{"name": "recsys-config", "behavior": "merge", "literals": [
            "KAFKA_BOOTSTRAP=b-1.recsys-msk.abc123.c2.kafka.us-east-1.amazonaws.com:9092,b-2.recsys-msk.abc123.c2.kafka.us-east-1.amazonaws.com:9092,b-3.recsys-msk.abc123.c2.kafka.us-east-1.amazonaws.com:9092",
            "SCHEMA_REGISTRY_URL=http://schema-registry.kafka:8081",
            "REDIS_URI=rediss://recsys-cache.abc123.clustercfg.use1.cache.amazonaws.com:6379",
            "QDRANT_HOST=qdrant.qdrant",
            "POSTGRES_URL=jdbc:postgresql://recsys.cluster-abc123.us-east-1.rds.amazonaws.com:5432/recsys?sslmode=require",
            "RECS_SECURITY_JWT_JWKS_URI=https://auth.example.com/.well-known/jwks.json",
            "RECS_SECURITY_JWT_ISSUER=https://auth.example.com/", "RECS_SECURITY_JWT_AUDIENCE=recsys"]}],
        "patches": [
            {"target": {"kind": "ServiceAccount", "name": "recsys"}, "patch": yaml.dump([{"op": "add", "path": "/metadata/annotations",
                "value": {"eks.amazonaws.com/role-arn": "arn:aws:iam::123456789012:role/recsys-prod-workloads"}}])},
            {"target": {"kind": "Deployment", "name": "recommendation-api"}, "patch": yaml.dump([{"op": "add", "path": "/spec/template/spec/containers/-", "value": sidecar}])},
            {"target": {"kind": "ScaledObject"}, "patch": yaml.dump([{"op": "replace", "path": "/spec/triggers/0/metadata/bootstrapServers",
                "value": "b-1.recsys-msk.abc123.c2.kafka.us-east-1.amazonaws.com:9092"}])},
        ],
    })
    (out / "qdrant-values.yaml").write_text(
        "# helm upgrade --install qdrant qdrant/qdrant -n qdrant -f deploy/k8s/overlays/prod-aws/qdrant-values.yaml\n"
        "# 5M items x 512 dims: ~10 GB vectors + HNSW; 3 replicas for HA, int8 quantization keeps RAM ~4 GB/node.\n"
        "replicaCount: 3\nresources:\n  requests: {cpu: \"2\", memory: 16Gi}\n  limits: {memory: 16Gi}\n"
        "persistence:\n  size: 100Gi\n  storageClassName: gp3\nconfig:\n  cluster:\n    enabled: true\n"
        "  storage:\n    optimizers:\n      # Fewer, larger segments; limit indexing threads so re-index storms don't starve search (R19).\n"
        "      max_optimization_threads: 2\n    performance:\n      max_search_threads: 0\n"
        "podDisruptionBudget:\n  enabled: true\n  maxUnavailable: 1\n"
    )


if __name__ == "__main__":
    base()
    monitoring()
    keda()
    local()
    prod()
    print("generated", sorted(str(p.relative_to(ROOT)) for p in ROOT.rglob("*.yaml")))
