# kind create cluster --name recsys --config deploy/k8s/overlays/local/kind-config.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: ./ml/models
        containerPath: /models
        readOnly: true
